# Generated by Django 5.2 on 2025-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(choices=[('centro', 'Centro'), ('bairros', 'Bairros'), ('periferia', 'Periferia')], max_length=20)),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finalidade', models.CharField(max_length=100)),
            ],
        ),
    ]
